# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
df = pd.read_csv("/content/flower csv.csv")
print(df.head())
print(df.info())
print(df.describe())